benchling/openapi-python-client

end_to_end_tests/fastapi_app/openapi.json
end_to_end_tests/golden-record/my_test_api_client/api/tests/get_user_list.py
end_to_end_tests/golden-record/my_test_api_client/models/__init__.py
end_to_end_tests/golden-record/my_test_api_client/models/integer_enum.py
openapi_python_client/parser/properties.py
openapi_python_client/templates/enum.pyi
tests/test_openapi_parser/test_properties.py

Previously, schema enums only actually supported string type values, though according to the [spec](https://json-schema.org/draft-04/json-schema-validation.html#rfc.section.5.5.1), values may be of any type. This fix adds support for non-string types in general, with the specific goal of supporting integer values in schema enums. 
- Modified the end-to-end tests to add an integer enum to the spec, which is then generated into client code. Ensured the enum was generated properly, and that existing enums' behavior was not changed. 
- Modified a test for the helper function `EnumProperty.values_from_list` to also operate on integer values, and ensured that the result is as expected.

fix: Support integer enums

---

openapi_python_client/parser/openapi.py
tests/test_openapi_parser/test_openapi.py

- In `resolve_references` - account for the fact tha we can't compare optional and required properties with `==` as they are `dataclass`es and the `required` value is different
- Combine required property list for `allOf`s elements that are schemas
- Fixes tests in the [`allof`](https://github.com/benchling/openapi-python-client/tree/allof) branch
- Adds new test for `Model.resolve_references` and ensures `resolve_references` is called by `Schemas.build`
Tests pass

fix: Bugfixes, tests for allOf functionality BNCH-15425

---

openapi_python_client/parser/openapi.py
tests/test_openapi_parser/test_openapi.py

When generating a client against the updated `Request` specs, I encountered an issue when an object is defined without properties. For example:
```
UserSummary:
allOf:
- $ref: '#/components/schemas/PartySummary'
- example:
id: ent_a0SApq3z
handle: lpasteur
name: Louis Pasteur
```
This fixes and adds an appropriate test.
- Unit tests
- Generate a client successfully against the updated `Requests` spec

Bug fix for allOf with no properties

---

openapi_python_client/parser/properties.py
openapi_python_client/templates/endpoint_macros.pyi
openapi_python_client/templates/model.pyi
openapi_python_client/templates/property_templates/date_property.pyi
openapi_python_client/templates/property_templates/datetime_property.pyi
openapi_python_client/templates/property_templates/dict_property.pyi
openapi_python_client/templates/property_templates/enum_property.pyi
openapi_python_client/templates/property_templates/file_property.pyi
openapi_python_client/templates/property_templates/list_property.pyi
openapi_python_client/templates/property_templates/ref_property.pyi
openapi_python_client/templates/property_templates/union_property.pyi
openapi_python_client/templates/types.py
tests/test_openapi_parser/test_properties.py

Fixes https://github.com/triaxtec/openapi-python-client/issues/205.
Introduces a new sentinel value, `UNSET` which becomes the new default for `nullable` fields which aren't `required`. If a field is set to this value, it will not be sent as part of the payload during serialization.
Since we still want to treat endpoint arguments and query params as they were originally without `Unset`, this logic has moved to `to_query_string` on `Property`.
Given a `str` type, a nullable property which isn't required might look something like:
```python
my_property: Union[str, None, Unset] = UNSET
```

Allow Unset values to avoid being send during serialization

---

openapi_python_client/parser/properties/__init__.py
poetry.lock
tests/test_parser/test_properties/test_model_property.py

Our code was not correctly generating models where `allOf` was done on a nested key, such as `NotFoundError`:
```
NotFoundError:
type: object
additionalProperties: false
properties:
error:
allOf:
- $ref: '#/components/schemas/BaseError'
- properties:
invalidId:
type: string
type:
type: string
enum:
- invalid_request_error
```
The generated model has no `error` property.
This bug also affects `ContainerContent`, `Folder`, `AssayRunSchema`, `AssayRequestSchema`, and potentially more.
This PR tries to fix the bug by changing `_property_from_data` and `build_model_property`.
- `poetry run task check`
- `poetry run task re`
- Made the changes in the `openapi-specs` submodule and rebuilt the client. Got these classes:
```
@attr.s(auto_attribs=True)
class NotFoundError:
"""  """
error: …
```

fix: Fix bug parsing `allOf` in nested keys BNCH-20174

---

end_to_end_tests/golden-record-custom/custom_e2e/models/__init__.py
end_to_end_tests/golden-record-custom/custom_e2e/models/a_model.py
end_to_end_tests/golden-record-custom/custom_e2e/models/a_model_model.py
end_to_end_tests/golden-record-custom/custom_e2e/models/a_model_not_required_model.py
end_to_end_tests/golden-record-custom/custom_e2e/models/a_model_not_required_nullable_model.py
end_to_end_tests/golden-record-custom/custom_e2e/models/a_model_nullable_model.py
end_to_end_tests/golden-record-custom/custom_e2e/models/model_with_primitive_additional_properties.py
end_to_end_tests/golden-record/my_test_api_client/models/__init__.py
end_to_end_tests/golden-record/my_test_api_client/models/a_model.py
end_to_end_tests/golden-record/my_test_api_client/models/a_model_model.py
end_to_end_tests/golden-record/my_test_api_client/models/a_model_not_required_model.py
end_to_end_tests/golden-record/my_test_api_client/models/a_model_not_required_nullable_model.py
end_to_end_tests/golden-record/my_test_api_client/models/a_model_nullable_model.py
end_to_end_tests/golden-record/my_test_api_client/models/model_with_primitive_additional_properties.py
end_to_end_tests/openapi.json
openapi_python_client/templates/property_templates/model_property.pyi
tests/test_parser/test_properties/test_model_property.py

Fixes the case when a model property is `nullable`, and adds E2E test coverage for this case.
I'm going to upstream this, but was planning to wait until https://github.com/triaxtec/openapi-python-client/pull/297 is merged (and didn't want to lump it into that PR to avoid scope creep).
Going to test by pulling this change into the `benchling-sdk` and confirming that integration tests pass (in particular for the `Container` and `Location` services).
Upstream PR: https://github.com/triaxtec/openapi-python-client/pull/315

fix: Fix optional model properties BNCH-20284

---

end_to_end_tests/golden-record-custom/custom_e2e/api/tests/defaults_tests_defaults_post.py
end_to_end_tests/golden-record-custom/custom_e2e/api/tests/optional_value_tests_optional_query_param.py
end_to_end_tests/golden-record/my_test_api_client/api/tests/defaults_tests_defaults_post.py
end_to_end_tests/golden-record/my_test_api_client/api/tests/optional_value_tests_optional_query_param.py
end_to_end_tests/openapi.json
openapi_python_client/parser/properties/model_property.py
openapi_python_client/parser/properties/property.py
openapi_python_client/templates/endpoint_macros.pyi

Fixes https://github.com/triaxtec/openapi-python-client/issues/295.
Upstream PR: https://github.com/triaxtec/openapi-python-client/pull/316
When I pulled this change into `openapi-specs` and made the changes in https://github.com/benchling/openapi-specs/pull/138, the generated code looked like this:
```
def _get_kwargs(
*,
client: Client,
next_token: Union[Unset, None, str] = UNSET,
page_size: Union[Unset, None, int] = 50,
sort: Union[Unset, None, ListCustomEntitiesSort] = ListCustomEntitiesSort.MODIFIEDATDESC,
modified_at: Union[Unset, None, str] = UNSET,
name: Union[Unset, None, str] = UNSET,
name_includes: Union[Unset, None, str] = UNSET,
folder_id: Union[Unset, None, str] = UNSET,
mentioned_in: Union[Unset, None, List[str]] = UNSET,
project_id: Union[Unset, None, str] = UNSET, …
```

feat: Serialize model query parameters with `style=form, explode=true` BNCH-18023

---

openapi_python_client/parser/properties/property.py
openapi_python_client/templates/property_templates/date_property.pyi
openapi_python_client/templates/property_templates/datetime_property.pyi
openapi_python_client/templates/property_templates/enum_property.pyi
openapi_python_client/templates/property_templates/file_property.pyi
openapi_python_client/templates/property_templates/list_property.pyi
openapi_python_client/templates/property_templates/model_property.pyi
openapi_python_client/templates/property_templates/union_property.pyi

Upstream generates the client this way, and in a parallel benchling-sdk ticket we'll be doing a conversion to UNSET for None parameters in the service layer.  Making this change in the fork in the meantime will keep us in a good state.

fix: Generate parameters to generated client without adding None BNCH-22940

---

openapi_python_client/parser/properties/__init__.py
openapi_python_client/parser/properties/property.py
openapi_python_client/parser/responses.py

To enable adding docstrings to python members in a generated way from the OpenAPI spec, add the description member to `Property` objects (which have been already parsed by the generator just not included in templates).
This is used in a corresponding change in benchling-sdk.

feat: Add description to Property definitions BNCH-29178

---

openapi_python_client/templates/pyproject.toml
pyproject.toml

Loosen the pinned `attrs` dependency
see also: [corresponding PR in benchling-sdk](https://github.com/benchling/benchling-sdk/pull/231)
**Testing**
Generate and test `benchling_api_client`

bugfix:broader attrs dependencies BNCH-36541

---

openapi_python_client/parser/properties/__init__.py

Updated the discriminator logic to handle the case where a discriminator maps several different discriminator values to the same schema, e.g.
```
BenchlingAppManifest:
properties:
configuration:
items:
anyOf:
- $ref: '#/components/schemas/SchemaDependency'
- $ref: '#/components/schemas/ResourceDependency'
discriminator:
mapping:
aa-sequence: '#/components/schemas/ResourceDependency'
assay-result: '#/components/schemas/ResourceDependency'
assay-result-schema: '#/components/schemas/SchemaDependency'
assay-run: '#/components/schemas/ResourceDependency'
assay-run-schema: '#/components/schemas/SchemaDependency'
...
propertyName: type
type: array
```
I verified this change by successfully regenerating models off of this change and inspecting the generated code. Snippet from …

fix: Support discriminators that map multiple keys to the same schema component BNCH-37105

---

poetry.lock
pyproject.toml

This PR raises the version of `importlib-metadata` in pyproject.toml to be 4.4 so that the Sphinx documentation generation library (which depends on `importlib-metadata` being 4.4 or greater) can be used in the Benchling SDK.
I have seen that there is another similar request by dependabot [here](https://github.com/benchling/openapi-python-client/pull/100) that is targeting branch `main-v.0.7.3`, but Benchling SDK seems to be currently pointing at the branch `benchling-sdk-m1-fixes-01282021` so I think it's best to handle this change separately from that existing PR.

Bump importlib-metadata to >=4.4 for compatibility with Sphinx in Benchling SDK

---

poetry.lock
pyproject.toml

When I bumped the version of `importlib_metadata`, I accidentally bumped a few other dependencies to their latest compatible versions. This may not necessarily be a problem, but I think it is better to limit updates to just the one I need, to avoid introducing unexpected issues. This PR updates the lock file to only include changes for `importlib_metadata`.

Remove unintended updates

---

poetry.lock
pyproject.toml

`httpx` changelog: https://github.com/encode/httpx/blob/master/CHANGELOG.md
There are some breaking changes, like parameter names that removed in `0.18.0` and `0.20.0`.
I looked through them and we should not be affected, and we should be able to be more confident after running our integration tests.
Given they do have breaking changes pre-1.0, I am continuing to declare an upper bound (`<=0.22.0`) as opposed to loosening even further.

chore: Loosen httpx dependency BNCH-38599

---

openapi_python_client/templates/pyproject.toml

Complements #115 to also bump up the dependency in the generated client (really, this is the only bump we needed).

chore: Bump up httpx in template / generated pyproject.yaml BNCH-38599

---

end_to_end_tests/golden-record-custom/pyproject.toml
end_to_end_tests/golden-record/pyproject.toml
openapi_python_client/parser/openapi.py
openapi_python_client/parser/responses.py
openapi_python_client/templates/endpoint_macros.pyi
openapi_python_client/templates/endpoint_module.pyi
openapi_python_client/templates/property_templates/model_property.pyi
poetry.lock
pyproject.toml
tests/test_parser/test_openapi.py
tests/test_parser/test_properties/test_init.py
tests/test_parser/test_responses.py
tests/test_templates/endpoint_module.py
tests/test_templates/test_endpoint_module.py
tests/test_templates/test_property_templates/test_date_property/test_date_property.py

Added text/yaml support.
Fixed some unit tests and added 1 to check for text/yaml support

feat: Added support for text/yaml in OpenAPI to be used in benchling-api-client BNCH-37249

---

openapi_python_client/templates/endpoint_module.pyi
openapi_python_client/templates/property_templates/model_property.pyi
poetry.lock
pyproject.toml
tests/test_templates/endpoint_module.py

As per https://github.com/benchling/benchling-api-client/pull/21#pullrequestreview-955605234 request. I've reverted back to using PyYaml.

fix: Fixed parsing logic for yaml files to use PyYaml instead of ruamel.yaml BNCH-37249

---

openapi_python_client/templates/pyproject.toml
poetry.lock
pyproject.toml

Upgrades dependencies for the generated API client template and the project:
- `httpx` minimum version increased due to `CVE-2021-41945`
- Python 3.6 is EOL and no longer supported, set 3.7 as minimum

chore: Upgrade project dependencies for generated client BNCH-43401

---

poetry.lock
pyproject.toml

In order for the SDK to get unpinned from attrs 21, benchling-api-client must be, which means this must be as well.

feat: Rev attrs package CUST-3710

---

end_to_end_tests/baseline_openapi_3.0.json
end_to_end_tests/baseline_openapi_3.1.yaml
end_to_end_tests/custom-templates-golden-record/my_test_api_client/api/responses/__init__.py
end_to_end_tests/golden-record/my_test_api_client/api/responses/reference_response.py
openapi_python_client/parser/bodies.py
openapi_python_client/parser/openapi.py
openapi_python_client/parser/properties/schemas.py
openapi_python_client/parser/responses.py
tests/test_parser/test_openapi.py
tests/test_parser/test_responses.py

Fixes https://github.com/openapi-generators/openapi-python-client/issues/1125.
I've also opened a PR from the same branch in the upstream repo ([here](https://github.com/openapi-generators/openapi-python-client/pull/1148)), but here I'm targeting it to our fork repo in against a new `2.x` branch (which I created by pulling the latest release code on `main` from the upstream repo). The `main` branch in our fork repo is still the same as it was, that is, a heavily modified fork of a very old version of the upstream repo.
See also: https://benchling.atlassian.net/wiki/spaces/AE/pages/730268159/Fixes+necessary+to+use+openapi-python-client+for+v3+API
**Why we need this fix:** The V3 API spec makes heavy use of reusable response definitions like this, so that we don't have to spell out the same …

fix: support $ref from endpoint response to components/responses BNCH-109662

---

pyproject.toml

This change is only for Benchling's internal use of the package and will not be submitted to the upstream repo. It's another prerequisite for us to be able to publish versions of the prod/2.x fork.
Basically, I forgot that our package-publishing pipeline uses a generic build frontend (`python -m build`) and needs a config hint as to which package management tool we're using, in this case poetry. I tested this change by running `python -m build` locally and it built a package.

eng: add build-system config for package BNCH-112051
